version: '3'
services:
  webapp:
    build: .
    ports:
      - "${PORT}:3000"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@postgres:5432/movies
      - LOG_LEVEL=${LOG_LEVEL}
      - OMDB_API_KEY=${OMDB_API_KEY}

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=movies

  migration:
    build: .
    command: ["yarn", "db:latest"]
    links:
      - postgres
    depends_on:
      - postgres
      - webapp
    environment:
      - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@postgres:5432/movies
      - LOG_LEVEL=${LOG_LEVEL}

volumes:
  postgres-data: {}
